### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by andreiw**
This gives me a clean build with gcc version 11.3.0 (Ubuntu 11.3.0-1ubuntu1~22.04.1). Builds on x86. Run on RV as well as the original.

### CODE REVIEW

**Comment by andreiw** [comment]
I've rebased this against your latest changes. Compiles without warnings and runs as much as before.

**Comment by andreiw** [comment]
ping

**Comment by andreiw** [comment]
ping

**Comment by haicheng-li** [comment]
merged in macrn-dev & main branch firstly already.

**Pull request merged**
